//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.imbag_types.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Nieuwe (versies van) objecten worden opgenomen op basis van daartoe aangewezen brondocumenten waarin de opname, mutatie of een in de historie plaatsen van gegevens van het object als zodanig is vastgelegd.
 * 
 * <p>Java class for Bron complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bron"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="documentdatum" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Datum"/&gt;
 *         &lt;element name="documentnummer" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Documentnummer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bron", propOrder = {
    "documentdatum",
    "documentnummer"
})
public class Bron {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String documentdatum;
    @XmlElement(required = true)
    protected String documentnummer;

    /**
     * Gets the value of the documentdatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentdatum() {
        return documentdatum;
    }

    /**
     * Sets the value of the documentdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentdatum(String value) {
        this.documentdatum = value;
    }

    /**
     * Gets the value of the documentnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentnummer() {
        return documentnummer;
    }

    /**
     * Sets the value of the documentnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentnummer(String value) {
        this.documentnummer = value;
    }

}
