//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.imbag_types.v20090901;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.kadaster.schemas.imbag.imbag_types.v20090901 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tijdvakgeldigheid_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901", "Tijdvakgeldigheid");
    private final static QName _Bron_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901", "Bron");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.kadaster.schemas.imbag.imbag_types.v20090901
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tijdvakgeldigheid }
     * 
     */
    public Tijdvakgeldigheid createTijdvakgeldigheid() {
        return new Tijdvakgeldigheid();
    }

    /**
     * Create an instance of {@link Bron }
     * 
     */
    public Bron createBron() {
        return new Bron();
    }

    /**
     * Create an instance of {@link PuntOfVlak }
     * 
     */
    public PuntOfVlak createPuntOfVlak() {
        return new PuntOfVlak();
    }

    /**
     * Create an instance of {@link VlakOfMultiVlak }
     * 
     */
    public VlakOfMultiVlak createVlakOfMultiVlak() {
        return new VlakOfMultiVlak();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tijdvakgeldigheid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Tijdvakgeldigheid }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901", name = "Tijdvakgeldigheid")
    public JAXBElement<Tijdvakgeldigheid> createTijdvakgeldigheid(Tijdvakgeldigheid value) {
        return new JAXBElement<Tijdvakgeldigheid>(_Tijdvakgeldigheid_QNAME, Tijdvakgeldigheid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bron }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Bron }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901", name = "Bron")
    public JAXBElement<Bron> createBron(Bron value) {
        return new JAXBElement<Bron>(_Bron_QNAME, Bron.class, null, value);
    }

}
