//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.imbag_types.v20090901;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusWoonplaats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusWoonplaats"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Woonplaats aangewezen"/&gt;
 *     &lt;enumeration value="Woonplaats ingetrokken"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StatusWoonplaats")
@XmlEnum
public enum StatusWoonplaats {

    @XmlEnumValue("Woonplaats aangewezen")
    WOONPLAATS_AANGEWEZEN("Woonplaats aangewezen"),
    @XmlEnumValue("Woonplaats ingetrokken")
    WOONPLAATS_INGETROKKEN("Woonplaats ingetrokken");
    private final String value;

    StatusWoonplaats(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusWoonplaats fromValue(String v) {
        for (StatusWoonplaats c: StatusWoonplaats.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
