//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.imbag_types.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Een periode waarin een of meer gegevens die worden bijgehouden over een object een wijziging hebben ondergaan.Formaat is DatumTijd en is 16 karakters gedefinieerd als (JJJJMMDDUUMMSSmm)
 * 
 * <p>Java class for Tijdvakgeldigheid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tijdvakgeldigheid"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="begindatumTijdvakGeldigheid" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}DatumTijd"/&gt;
 *         &lt;element name="einddatumTijdvakGeldigheid" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}DatumTijd" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tijdvakgeldigheid", propOrder = {
    "begindatumTijdvakGeldigheid",
    "einddatumTijdvakGeldigheid"
})
public class Tijdvakgeldigheid {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String begindatumTijdvakGeldigheid;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String einddatumTijdvakGeldigheid;

    /**
     * Gets the value of the begindatumTijdvakGeldigheid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegindatumTijdvakGeldigheid() {
        return begindatumTijdvakGeldigheid;
    }

    /**
     * Sets the value of the begindatumTijdvakGeldigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBegindatumTijdvakGeldigheid(String value) {
        this.begindatumTijdvakGeldigheid = value;
    }

    /**
     * Gets the value of the einddatumTijdvakGeldigheid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEinddatumTijdvakGeldigheid() {
        return einddatumTijdvakGeldigheid;
    }

    /**
     * Sets the value of the einddatumTijdvakGeldigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEinddatumTijdvakGeldigheid(String value) {
        this.einddatumTijdvakGeldigheid = value;
    }

}
