//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_deelbestand_lvc.v20090901;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.kadaster.schemas.bag_verstrekkingen.extract_deelbestand_lvc.v20090901 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.kadaster.schemas.bag_verstrekkingen.extract_deelbestand_lvc.v20090901
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BAGExtractDeelbestandLVC }
     * 
     */
    public BAGExtractDeelbestandLVC createBAGExtractDeelbestandLVC() {
        return new BAGExtractDeelbestandLVC();
    }

    /**
     * Create an instance of {@link BAGExtractDeelbestandLVC.Antwoord }
     * 
     */
    public BAGExtractDeelbestandLVC.Antwoord createBAGExtractDeelbestandLVCAntwoord() {
        return new BAGExtractDeelbestandLVC.Antwoord();
    }

    /**
     * Create an instance of {@link BAGExtractDeelbestandLVC.Antwoord.Vraag }
     * 
     */
    public BAGExtractDeelbestandLVC.Antwoord.Vraag createBAGExtractDeelbestandLVCAntwoordVraag() {
        return new BAGExtractDeelbestandLVC.Antwoord.Vraag();
    }

    /**
     * Create an instance of {@link BAGExtractDeelbestandLVC.Antwoord.Producten }
     * 
     */
    public BAGExtractDeelbestandLVC.Antwoord.Producten createBAGExtractDeelbestandLVCAntwoordProducten() {
        return new BAGExtractDeelbestandLVC.Antwoord.Producten();
    }

}
