//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.lvc.v20090901.Ligplaats;
import nl.kadaster.schemas.imbag.lvc.v20090901.Nummeraanduiding;
import nl.kadaster.schemas.imbag.lvc.v20090901.OpenbareRuimte;
import nl.kadaster.schemas.imbag.lvc.v20090901.Pand;
import nl.kadaster.schemas.imbag.lvc.v20090901.Standplaats;
import nl.kadaster.schemas.imbag.lvc.v20090901.Verblijfsobject;
import nl.kadaster.schemas.imbag.lvc.v20090901.Woonplaats;


/**
 * <p>Java class for LVC-product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LVC-product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}_product"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Woonplaats" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}OpenbareRuimte" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Nummeraanduiding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Verblijfsobject" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Pand" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Standplaats" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Ligplaats" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LVC-product", propOrder = {
    "woonplaats",
    "openbareRuimte",
    "nummeraanduiding",
    "verblijfsobject",
    "pand",
    "standplaats",
    "ligplaats"
})
public class LVCProduct
    extends Product
{

    @XmlElement(name = "Woonplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Woonplaats> woonplaats;
    @XmlElement(name = "OpenbareRuimte", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<OpenbareRuimte> openbareRuimte;
    @XmlElement(name = "Nummeraanduiding", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Nummeraanduiding> nummeraanduiding;
    @XmlElement(name = "Verblijfsobject", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Verblijfsobject> verblijfsobject;
    @XmlElement(name = "Pand", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Pand> pand;
    @XmlElement(name = "Standplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Standplaats> standplaats;
    @XmlElement(name = "Ligplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected List<Ligplaats> ligplaats;

    /**
     * Gets the value of the woonplaats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the woonplaats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWoonplaats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Woonplaats }
     * 
     * 
     */
    public List<Woonplaats> getWoonplaats() {
        if (woonplaats == null) {
            woonplaats = new ArrayList<Woonplaats>();
        }
        return this.woonplaats;
    }

    /**
     * Gets the value of the openbareRuimte property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the openbareRuimte property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpenbareRuimte().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpenbareRuimte }
     * 
     * 
     */
    public List<OpenbareRuimte> getOpenbareRuimte() {
        if (openbareRuimte == null) {
            openbareRuimte = new ArrayList<OpenbareRuimte>();
        }
        return this.openbareRuimte;
    }

    /**
     * Gets the value of the nummeraanduiding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nummeraanduiding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNummeraanduiding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nummeraanduiding }
     * 
     * 
     */
    public List<Nummeraanduiding> getNummeraanduiding() {
        if (nummeraanduiding == null) {
            nummeraanduiding = new ArrayList<Nummeraanduiding>();
        }
        return this.nummeraanduiding;
    }

    /**
     * Gets the value of the verblijfsobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verblijfsobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerblijfsobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Verblijfsobject }
     * 
     * 
     */
    public List<Verblijfsobject> getVerblijfsobject() {
        if (verblijfsobject == null) {
            verblijfsobject = new ArrayList<Verblijfsobject>();
        }
        return this.verblijfsobject;
    }

    /**
     * Gets the value of the pand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pand }
     * 
     * 
     */
    public List<Pand> getPand() {
        if (pand == null) {
            pand = new ArrayList<Pand>();
        }
        return this.pand;
    }

    /**
     * Gets the value of the standplaats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standplaats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandplaats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Standplaats }
     * 
     * 
     */
    public List<Standplaats> getStandplaats() {
        if (standplaats == null) {
            standplaats = new ArrayList<Standplaats>();
        }
        return this.standplaats;
    }

    /**
     * Gets the value of the ligplaats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ligplaats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLigplaats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ligplaats }
     * 
     * 
     */
    public List<Ligplaats> getLigplaats() {
        if (ligplaats == null) {
            ligplaats = new ArrayList<Ligplaats>();
        }
        return this.ligplaats;
    }

}
