//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.lvc.v20090901.Ligplaats;
import nl.kadaster.schemas.imbag.lvc.v20090901.Nummeraanduiding;
import nl.kadaster.schemas.imbag.lvc.v20090901.OpenbareRuimte;
import nl.kadaster.schemas.imbag.lvc.v20090901.Pand;
import nl.kadaster.schemas.imbag.lvc.v20090901.Standplaats;
import nl.kadaster.schemas.imbag.lvc.v20090901.Verblijfsobject;
import nl.kadaster.schemas.imbag.lvc.v20090901.Woonplaats;


/**
 * <p>Java class for LVC-voorkomen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LVC-voorkomen"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Woonplaats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}OpenbareRuimte" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Nummeraanduiding" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Verblijfsobject" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Pand" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Standplaats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}Ligplaats" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LVC-voorkomen", propOrder = {
    "woonplaats",
    "openbareRuimte",
    "nummeraanduiding",
    "verblijfsobject",
    "pand",
    "standplaats",
    "ligplaats"
})
public class LVCVoorkomen {

    @XmlElement(name = "Woonplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Woonplaats woonplaats;
    @XmlElement(name = "OpenbareRuimte", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected OpenbareRuimte openbareRuimte;
    @XmlElement(name = "Nummeraanduiding", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Nummeraanduiding nummeraanduiding;
    @XmlElement(name = "Verblijfsobject", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Verblijfsobject verblijfsobject;
    @XmlElement(name = "Pand", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Pand pand;
    @XmlElement(name = "Standplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Standplaats standplaats;
    @XmlElement(name = "Ligplaats", namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901")
    protected Ligplaats ligplaats;

    /**
     * Gets the value of the woonplaats property.
     * 
     * @return
     *     possible object is
     *     {@link Woonplaats }
     *     
     */
    public Woonplaats getWoonplaats() {
        return woonplaats;
    }

    /**
     * Sets the value of the woonplaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Woonplaats }
     *     
     */
    public void setWoonplaats(Woonplaats value) {
        this.woonplaats = value;
    }

    /**
     * Gets the value of the openbareRuimte property.
     * 
     * @return
     *     possible object is
     *     {@link OpenbareRuimte }
     *     
     */
    public OpenbareRuimte getOpenbareRuimte() {
        return openbareRuimte;
    }

    /**
     * Sets the value of the openbareRuimte property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenbareRuimte }
     *     
     */
    public void setOpenbareRuimte(OpenbareRuimte value) {
        this.openbareRuimte = value;
    }

    /**
     * Gets the value of the nummeraanduiding property.
     * 
     * @return
     *     possible object is
     *     {@link Nummeraanduiding }
     *     
     */
    public Nummeraanduiding getNummeraanduiding() {
        return nummeraanduiding;
    }

    /**
     * Sets the value of the nummeraanduiding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nummeraanduiding }
     *     
     */
    public void setNummeraanduiding(Nummeraanduiding value) {
        this.nummeraanduiding = value;
    }

    /**
     * Gets the value of the verblijfsobject property.
     * 
     * @return
     *     possible object is
     *     {@link Verblijfsobject }
     *     
     */
    public Verblijfsobject getVerblijfsobject() {
        return verblijfsobject;
    }

    /**
     * Sets the value of the verblijfsobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verblijfsobject }
     *     
     */
    public void setVerblijfsobject(Verblijfsobject value) {
        this.verblijfsobject = value;
    }

    /**
     * Gets the value of the pand property.
     * 
     * @return
     *     possible object is
     *     {@link Pand }
     *     
     */
    public Pand getPand() {
        return pand;
    }

    /**
     * Sets the value of the pand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pand }
     *     
     */
    public void setPand(Pand value) {
        this.pand = value;
    }

    /**
     * Gets the value of the standplaats property.
     * 
     * @return
     *     possible object is
     *     {@link Standplaats }
     *     
     */
    public Standplaats getStandplaats() {
        return standplaats;
    }

    /**
     * Sets the value of the standplaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Standplaats }
     *     
     */
    public void setStandplaats(Standplaats value) {
        this.standplaats = value;
    }

    /**
     * Gets the value of the ligplaats property.
     * 
     * @return
     *     possible object is
     *     {@link Ligplaats }
     *     
     */
    public Ligplaats getLigplaats() {
        return ligplaats;
    }

    /**
     * Sets the value of the ligplaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ligplaats }
     *     
     */
    public void setLigplaats(Ligplaats value) {
        this.ligplaats = value;
    }

}
