//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mutatie-product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mutatie-product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}_product"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}Verwerking"/&gt;
 *         &lt;element name="Origineel" type="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}LVC-voorkomen" minOccurs="0"/&gt;
 *         &lt;element name="Wijziging" type="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}LVC-voorkomen" minOccurs="0"/&gt;
 *         &lt;element name="Nieuw" type="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}LVC-voorkomen" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mutatie-product", propOrder = {
    "verwerking",
    "origineel",
    "wijziging",
    "nieuw"
})
public class MutatieProduct
    extends Product
{

    @XmlElement(name = "Verwerking", required = true)
    protected Verwerking verwerking;
    @XmlElement(name = "Origineel")
    protected LVCVoorkomen origineel;
    @XmlElement(name = "Wijziging")
    protected LVCVoorkomen wijziging;
    @XmlElement(name = "Nieuw")
    protected LVCVoorkomen nieuw;

    /**
     * Gets the value of the verwerking property.
     * 
     * @return
     *     possible object is
     *     {@link Verwerking }
     *     
     */
    public Verwerking getVerwerking() {
        return verwerking;
    }

    /**
     * Sets the value of the verwerking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verwerking }
     *     
     */
    public void setVerwerking(Verwerking value) {
        this.verwerking = value;
    }

    /**
     * Gets the value of the origineel property.
     * 
     * @return
     *     possible object is
     *     {@link LVCVoorkomen }
     *     
     */
    public LVCVoorkomen getOrigineel() {
        return origineel;
    }

    /**
     * Sets the value of the origineel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVCVoorkomen }
     *     
     */
    public void setOrigineel(LVCVoorkomen value) {
        this.origineel = value;
    }

    /**
     * Gets the value of the wijziging property.
     * 
     * @return
     *     possible object is
     *     {@link LVCVoorkomen }
     *     
     */
    public LVCVoorkomen getWijziging() {
        return wijziging;
    }

    /**
     * Sets the value of the wijziging property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVCVoorkomen }
     *     
     */
    public void setWijziging(LVCVoorkomen value) {
        this.wijziging = value;
    }

    /**
     * Gets the value of the nieuw property.
     * 
     * @return
     *     possible object is
     *     {@link LVCVoorkomen }
     *     
     */
    public LVCVoorkomen getNieuw() {
        return nieuw;
    }

    /**
     * Sets the value of the nieuw property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVCVoorkomen }
     *     
     */
    public void setNieuw(LVCVoorkomen value) {
        this.nieuw = value;
    }

}
