//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LVCProduct_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "LVC-product");
    private final static QName _APDProduct_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "APD-product");
    private final static QName _MutatieProduct_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "Mutatie-product");
    private final static QName _LVCVoorkomen_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "LVC-voorkomen");
    private final static QName _Verwerking_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "Verwerking");
    private final static QName _ObjectType_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "ObjectType");
    private final static QName _Woonplaats_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "Woonplaats");
    private final static QName _WoonplaatsIdentificatie_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "WoonplaatsIdentificatie");
    private final static QName _WoonplaatsNaam_QNAME = new QName("http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", "WoonplaatsNaam");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LVCProduct }
     * 
     */
    public LVCProduct createLVCProduct() {
        return new LVCProduct();
    }

    /**
     * Create an instance of {@link MutatieProduct }
     * 
     */
    public MutatieProduct createMutatieProduct() {
        return new MutatieProduct();
    }

    /**
     * Create an instance of {@link LVCVoorkomen }
     * 
     */
    public LVCVoorkomen createLVCVoorkomen() {
        return new LVCVoorkomen();
    }

    /**
     * Create an instance of {@link Verwerking }
     * 
     */
    public Verwerking createVerwerking() {
        return new Verwerking();
    }

    /**
     * Create an instance of {@link Woonplaats }
     * 
     */
    public Woonplaats createWoonplaats() {
        return new Woonplaats();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LVCProduct }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LVCProduct }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "LVC-product")
    public JAXBElement<LVCProduct> createLVCProduct(LVCProduct value) {
        return new JAXBElement<LVCProduct>(_LVCProduct_QNAME, LVCProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LVCProduct }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LVCProduct }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "APD-product")
    public JAXBElement<LVCProduct> createAPDProduct(LVCProduct value) {
        return new JAXBElement<LVCProduct>(_APDProduct_QNAME, LVCProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MutatieProduct }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MutatieProduct }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "Mutatie-product")
    public JAXBElement<MutatieProduct> createMutatieProduct(MutatieProduct value) {
        return new JAXBElement<MutatieProduct>(_MutatieProduct_QNAME, MutatieProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LVCVoorkomen }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LVCVoorkomen }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "LVC-voorkomen")
    public JAXBElement<LVCVoorkomen> createLVCVoorkomen(LVCVoorkomen value) {
        return new JAXBElement<LVCVoorkomen>(_LVCVoorkomen_QNAME, LVCVoorkomen.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Verwerking }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Verwerking }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "Verwerking")
    public JAXBElement<Verwerking> createVerwerking(Verwerking value) {
        return new JAXBElement<Verwerking>(_Verwerking_QNAME, Verwerking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "ObjectType")
    public JAXBElement<String> createObjectType(String value) {
        return new JAXBElement<String>(_ObjectType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Woonplaats }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Woonplaats }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "Woonplaats")
    public JAXBElement<Woonplaats> createWoonplaats(Woonplaats value) {
        return new JAXBElement<Woonplaats>(_Woonplaats_QNAME, Woonplaats.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "WoonplaatsIdentificatie")
    public JAXBElement<String> createWoonplaatsIdentificatie(String value) {
        return new JAXBElement<String>(_WoonplaatsIdentificatie_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901", name = "WoonplaatsNaam")
    public JAXBElement<String> createWoonplaatsNaam(String value) {
        return new JAXBElement<String>(_WoonplaatsNaam_QNAME, String.class, null, value);
    }

}
