//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Stuurgegevens t.b.v. verwerking van een LVC_Mutatie
 * 
 * <p>Java class for Verwerking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Verwerking"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TijdstipVerwerking" type="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}TijdstipVerwerking"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}ObjectType"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}Woonplaats" minOccurs="0"/&gt;
 *         &lt;element name="VolgnrVerwerking" type="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}VolgnummerVerwerking"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Verwerking", propOrder = {
    "tijdstipVerwerking",
    "objectType",
    "woonplaats",
    "volgnrVerwerking"
})
public class Verwerking {

    @XmlElement(name = "TijdstipVerwerking", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tijdstipVerwerking;
    @XmlElement(name = "ObjectType", required = true)
    protected String objectType;
    @XmlElement(name = "Woonplaats")
    protected Woonplaats woonplaats;
    @XmlElement(name = "VolgnrVerwerking", required = true)
    protected BigInteger volgnrVerwerking;

    /**
     * Gets the value of the tijdstipVerwerking property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTijdstipVerwerking() {
        return tijdstipVerwerking;
    }

    /**
     * Sets the value of the tijdstipVerwerking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTijdstipVerwerking(XMLGregorianCalendar value) {
        this.tijdstipVerwerking = value;
    }

    /**
     * Het BAG Object type voor de verwerking van een LVC_Mutatie. Alle verwerkingen binnen 1 LVC_mutatie zijn van hetzelfde objecttype. 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * De woonplaats waartoe het  object, waarop de mutatie betrekking heeft, behoort 
     * 
     * @return
     *     possible object is
     *     {@link Woonplaats }
     *     
     */
    public Woonplaats getWoonplaats() {
        return woonplaats;
    }

    /**
     * Sets the value of the woonplaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Woonplaats }
     *     
     */
    public void setWoonplaats(Woonplaats value) {
        this.woonplaats = value;
    }

    /**
     * Gets the value of the volgnrVerwerking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVolgnrVerwerking() {
        return volgnrVerwerking;
    }

    /**
     * Sets the value of the volgnrVerwerking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVolgnrVerwerking(BigInteger value) {
        this.volgnrVerwerking = value;
    }

}
