//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_producten_lvc.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Woonplaats complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Woonplaats"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}WoonplaatsIdentificatie"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-producten-lvc/v20090901}WoonplaatsNaam" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Woonplaats", propOrder = {
    "woonplaatsIdentificatie",
    "woonplaatsNaam"
})
public class Woonplaats {

    @XmlElement(name = "WoonplaatsIdentificatie", required = true)
    protected String woonplaatsIdentificatie;
    @XmlElement(name = "WoonplaatsNaam")
    protected String woonplaatsNaam;

    /**
     * Gets the value of the woonplaatsIdentificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoonplaatsIdentificatie() {
        return woonplaatsIdentificatie;
    }

    /**
     * Sets the value of the woonplaatsIdentificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoonplaatsIdentificatie(String value) {
        this.woonplaatsIdentificatie = value;
    }

    /**
     * Gets the value of the woonplaatsNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoonplaatsNaam() {
        return woonplaatsNaam;
    }

    /**
     * Sets the value of the woonplaatsNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoonplaatsNaam(String value) {
        this.woonplaatsNaam = value;
    }

}
