//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.VlakOfMultiVlak;


/**
 * <p>Java class for Gebied-GEO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gebied-GEO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Gebied"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gebiedTypeGeometrie" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Polygoon"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}WoonplaatsCollectie" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gebied-GEO", propOrder = {
    "gebiedTypeGeometrie",
    "polygoon",
    "woonplaatsCollectie"
})
public class GebiedGEO
    extends Gebied
{

    @XmlElement(defaultValue = "0")
    protected boolean gebiedTypeGeometrie;
    @XmlElement(name = "Polygoon", required = true)
    protected VlakOfMultiVlak polygoon;
    @XmlElement(name = "WoonplaatsCollectie")
    protected WoonplaatsCollectie woonplaatsCollectie;

    /**
     * Gets the value of the gebiedTypeGeometrie property.
     * 
     */
    public boolean isGebiedTypeGeometrie() {
        return gebiedTypeGeometrie;
    }

    /**
     * Sets the value of the gebiedTypeGeometrie property.
     * 
     */
    public void setGebiedTypeGeometrie(boolean value) {
        this.gebiedTypeGeometrie = value;
    }

    /**
     * Gets the value of the polygoon property.
     * 
     * @return
     *     possible object is
     *     {@link VlakOfMultiVlak }
     *     
     */
    public VlakOfMultiVlak getPolygoon() {
        return polygoon;
    }

    /**
     * Sets the value of the polygoon property.
     * 
     * @param value
     *     allowed object is
     *     {@link VlakOfMultiVlak }
     *     
     */
    public void setPolygoon(VlakOfMultiVlak value) {
        this.polygoon = value;
    }

    /**
     * Aanvullende gegevens. Het gevraagde gebied is vertaald naar een woonplaatscollectie. 
     * 
     * @return
     *     possible object is
     *     {@link WoonplaatsCollectie }
     *     
     */
    public WoonplaatsCollectie getWoonplaatsCollectie() {
        return woonplaatsCollectie;
    }

    /**
     * Sets the value of the woonplaatsCollectie property.
     * 
     * @param value
     *     allowed object is
     *     {@link WoonplaatsCollectie }
     *     
     */
    public void setWoonplaatsCollectie(WoonplaatsCollectie value) {
        this.woonplaatsCollectie = value;
    }

}
