//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Gebied-Registratief complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gebied-Registratief"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Gebied-NLD"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Gebied-WPL"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Gebied-GEO"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gebied-Registratief", propOrder = {
    "gebiedNLD",
    "gebiedWPL",
    "gebiedGEO"
})
public class GebiedRegistratief {

    @XmlElement(name = "Gebied-NLD")
    protected GebiedNLD gebiedNLD;
    @XmlElement(name = "Gebied-WPL")
    protected GebiedWPL gebiedWPL;
    @XmlElement(name = "Gebied-GEO")
    protected GebiedGEO gebiedGEO;

    /**
     * Gebied: Heel Nederland. 
     * 
     * @return
     *     possible object is
     *     {@link GebiedNLD }
     *     
     */
    public GebiedNLD getGebiedNLD() {
        return gebiedNLD;
    }

    /**
     * Sets the value of the gebiedNLD property.
     * 
     * @param value
     *     allowed object is
     *     {@link GebiedNLD }
     *     
     */
    public void setGebiedNLD(GebiedNLD value) {
        this.gebiedNLD = value;
    }

    /**
     * Gebied: Woonplaats(en)
     * 
     * @return
     *     possible object is
     *     {@link GebiedWPL }
     *     
     */
    public GebiedWPL getGebiedWPL() {
        return gebiedWPL;
    }

    /**
     * Sets the value of the gebiedWPL property.
     * 
     * @param value
     *     allowed object is
     *     {@link GebiedWPL }
     *     
     */
    public void setGebiedWPL(GebiedWPL value) {
        this.gebiedWPL = value;
    }

    /**
     * Gebied: polygoon (geometrisch)
     * 
     * @return
     *     possible object is
     *     {@link GebiedGEO }
     *     
     */
    public GebiedGEO getGebiedGEO() {
        return gebiedGEO;
    }

    /**
     * Sets the value of the gebiedGEO property.
     * 
     * @param value
     *     allowed object is
     *     {@link GebiedGEO }
     *     
     */
    public void setGebiedGEO(GebiedGEO value) {
        this.gebiedGEO = value;
    }

}
