//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Gebied-WPL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gebied-WPL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Gebied"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gebiedTypeWoonplaats" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}WoonplaatsCollectie"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gebied-WPL", propOrder = {
    "gebiedTypeWoonplaats",
    "woonplaatsCollectie"
})
public class GebiedWPL
    extends Gebied
{

    @XmlElement(defaultValue = "0")
    protected boolean gebiedTypeWoonplaats;
    @XmlElement(name = "WoonplaatsCollectie", required = true)
    protected WoonplaatsCollectie woonplaatsCollectie;

    /**
     * Gets the value of the gebiedTypeWoonplaats property.
     * 
     */
    public boolean isGebiedTypeWoonplaats() {
        return gebiedTypeWoonplaats;
    }

    /**
     * Sets the value of the gebiedTypeWoonplaats property.
     * 
     */
    public void setGebiedTypeWoonplaats(boolean value) {
        this.gebiedTypeWoonplaats = value;
    }

    /**
     * Het gevraagde gebied is een woonplaatscollectie. 
     * 
     * @return
     *     possible object is
     *     {@link WoonplaatsCollectie }
     *     
     */
    public WoonplaatsCollectie getWoonplaatsCollectie() {
        return woonplaatsCollectie;
    }

    /**
     * Sets the value of the woonplaatsCollectie property.
     * 
     * @param value
     *     allowed object is
     *     {@link WoonplaatsCollectie }
     *     
     */
    public void setWoonplaatsCollectie(WoonplaatsCollectie value) {
        this.woonplaatsCollectie = value;
    }

}
