//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Gebied complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gebied"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}GebiedIdentificatie"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}GebiedNaam" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gebied", propOrder = {
    "gebiedIdentificatie",
    "gebiedNaam"
})
@XmlSeeAlso({
    GebiedWPL.class,
    GebiedNLD.class,
    GebiedGEO.class
})
public class Gebied {

    @XmlElement(name = "GebiedIdentificatie", required = true)
    protected String gebiedIdentificatie;
    @XmlElement(name = "GebiedNaam")
    protected String gebiedNaam;

    /**
     * Gets the value of the gebiedIdentificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGebiedIdentificatie() {
        return gebiedIdentificatie;
    }

    /**
     * Sets the value of the gebiedIdentificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGebiedIdentificatie(String value) {
        this.gebiedIdentificatie = value;
    }

    /**
     * Gets the value of the gebiedNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGebiedNaam() {
        return gebiedNaam;
    }

    /**
     * Sets the value of the gebiedNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGebiedNaam(String value) {
        this.gebiedNaam = value;
    }

}
