//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Leverfrequentie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Leverfrequentie"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="eenmalig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="periode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="aantal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="looptijdTot" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="dag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                     &lt;element name="week" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                     &lt;element name="maand" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Leverfrequentie", propOrder = {
    "eenmalig",
    "periode"
})
public class Leverfrequentie {

    @XmlElement(defaultValue = "0")
    protected Boolean eenmalig;
    protected Leverfrequentie.Periode periode;

    /**
     * Gets the value of the eenmalig property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEenmalig() {
        return eenmalig;
    }

    /**
     * Sets the value of the eenmalig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEenmalig(Boolean value) {
        this.eenmalig = value;
    }

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *     possible object is
     *     {@link Leverfrequentie.Periode }
     *     
     */
    public Leverfrequentie.Periode getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leverfrequentie.Periode }
     *     
     */
    public void setPeriode(Leverfrequentie.Periode value) {
        this.periode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="aantal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="looptijdTot" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;choice&gt;
     *           &lt;element name="dag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *           &lt;element name="week" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *           &lt;element name="maand" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aantal",
        "looptijdTot",
        "dag",
        "week",
        "maand"
    })
    public static class Periode {

        @XmlElement(defaultValue = "0")
        protected BigInteger aantal;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar looptijdTot;
        @XmlElement(defaultValue = "0")
        protected Boolean dag;
        @XmlElement(defaultValue = "0")
        protected Boolean week;
        @XmlElement(defaultValue = "0")
        protected Boolean maand;

        /**
         * Gets the value of the aantal property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAantal() {
            return aantal;
        }

        /**
         * Sets the value of the aantal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAantal(BigInteger value) {
            this.aantal = value;
        }

        /**
         * Gets the value of the looptijdTot property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLooptijdTot() {
            return looptijdTot;
        }

        /**
         * Sets the value of the looptijdTot property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLooptijdTot(XMLGregorianCalendar value) {
            this.looptijdTot = value;
        }

        /**
         * Gets the value of the dag property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isDag() {
            return dag;
        }

        /**
         * Sets the value of the dag property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDag(Boolean value) {
            this.dag = value;
        }

        /**
         * Gets the value of the week property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isWeek() {
            return week;
        }

        /**
         * Sets the value of the week property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setWeek(Boolean value) {
            this.week = value;
        }

        /**
         * Gets the value of the maand property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMaand() {
            return maand;
        }

        /**
         * Sets the value of the maand property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMaand(Boolean value) {
            this.maand = value;
        }

    }

}
