//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for LVC-Extract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LVC-Extract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="gegVarLevenscyclus" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="gegVarLevenscyclusVanaf" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *             &lt;element name="peildatumVanaf" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Datum" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="productcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}StandTechnischeDatum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LVC-Extract", propOrder = {
    "gegVarLevenscyclus",
    "gegVarLevenscyclusVanaf",
    "peildatumVanaf",
    "productcode",
    "standTechnischeDatum"
})
public class LVCExtract {

    @XmlElement(defaultValue = "0")
    protected Boolean gegVarLevenscyclus;
    @XmlElement(defaultValue = "0")
    protected Boolean gegVarLevenscyclusVanaf;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String peildatumVanaf;
    protected String productcode;
    @XmlElement(name = "StandTechnischeDatum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String standTechnischeDatum;

    /**
     * Gets the value of the gegVarLevenscyclus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGegVarLevenscyclus() {
        return gegVarLevenscyclus;
    }

    /**
     * Sets the value of the gegVarLevenscyclus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGegVarLevenscyclus(Boolean value) {
        this.gegVarLevenscyclus = value;
    }

    /**
     * Gets the value of the gegVarLevenscyclusVanaf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGegVarLevenscyclusVanaf() {
        return gegVarLevenscyclusVanaf;
    }

    /**
     * Sets the value of the gegVarLevenscyclusVanaf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGegVarLevenscyclusVanaf(Boolean value) {
        this.gegVarLevenscyclusVanaf = value;
    }

    /**
     * Gets the value of the peildatumVanaf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeildatumVanaf() {
        return peildatumVanaf;
    }

    /**
     * Sets the value of the peildatumVanaf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeildatumVanaf(String value) {
        this.peildatumVanaf = value;
    }

    /**
     * Gets the value of the productcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * Sets the value of the productcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductcode(String value) {
        this.productcode = value;
    }

    /**
     * Gets the value of the standTechnischeDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandTechnischeDatum() {
        return standTechnischeDatum;
    }

    /**
     * Sets the value of the standTechnischeDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandTechnischeDatum(String value) {
        this.standTechnischeDatum = value;
    }

}
