//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mutatievorm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mutatievorm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="mutatiebestand" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *           &lt;element name="mutatieberichten" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mutatievorm", propOrder = {
    "mutatiebestand",
    "mutatieberichten"
})
public class Mutatievorm {

    @XmlElement(defaultValue = "0")
    protected Boolean mutatiebestand;
    @XmlElement(defaultValue = "0")
    protected Boolean mutatieberichten;

    /**
     * Gets the value of the mutatiebestand property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMutatiebestand() {
        return mutatiebestand;
    }

    /**
     * Sets the value of the mutatiebestand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMutatiebestand(Boolean value) {
        this.mutatiebestand = value;
    }

    /**
     * Gets the value of the mutatieberichten property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMutatieberichten() {
        return mutatieberichten;
    }

    /**
     * Sets the value of the mutatieberichten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMutatieberichten(Boolean value) {
        this.mutatieberichten = value;
    }

}
