//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Mutatieperiode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mutatieperiode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}MutatiedatumVanaf"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}MutatiedatumTot"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mutatieperiode", propOrder = {
    "mutatiedatumVanaf",
    "mutatiedatumTot"
})
public class Mutatieperiode {

    @XmlElement(name = "MutatiedatumVanaf", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mutatiedatumVanaf;
    @XmlElement(name = "MutatiedatumTot", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mutatiedatumTot;

    /**
     * Gets the value of the mutatiedatumVanaf property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutatiedatumVanaf() {
        return mutatiedatumVanaf;
    }

    /**
     * Sets the value of the mutatiedatumVanaf property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutatiedatumVanaf(XMLGregorianCalendar value) {
        this.mutatiedatumVanaf = value;
    }

    /**
     * Gets the value of the mutatiedatumTot property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutatiedatumTot() {
        return mutatiedatumTot;
    }

    /**
     * Sets the value of the mutatiedatumTot property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutatiedatumTot(XMLGregorianCalendar value) {
        this.mutatiedatumTot = value;
    }

}
