//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MUT-Extract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MUT-Extract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mutaties" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Mutatievorm"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Mutatieperiode" minOccurs="0"/&gt;
 *         &lt;element name="productcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MUT-Extract", propOrder = {
    "mutaties",
    "mutatievorm",
    "mutatieperiode",
    "productcode"
})
public class MUTExtract {

    @XmlElement(defaultValue = "0")
    protected boolean mutaties;
    @XmlElement(name = "Mutatievorm", required = true)
    protected Mutatievorm mutatievorm;
    @XmlElement(name = "Mutatieperiode")
    protected Mutatieperiode mutatieperiode;
    protected String productcode;

    /**
     * Gets the value of the mutaties property.
     * 
     */
    public boolean isMutaties() {
        return mutaties;
    }

    /**
     * Sets the value of the mutaties property.
     * 
     */
    public void setMutaties(boolean value) {
        this.mutaties = value;
    }

    /**
     * Gets the value of the mutatievorm property.
     * 
     * @return
     *     possible object is
     *     {@link Mutatievorm }
     *     
     */
    public Mutatievorm getMutatievorm() {
        return mutatievorm;
    }

    /**
     * Sets the value of the mutatievorm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mutatievorm }
     *     
     */
    public void setMutatievorm(Mutatievorm value) {
        this.mutatievorm = value;
    }

    /**
     * Gets the value of the mutatieperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Mutatieperiode }
     *     
     */
    public Mutatieperiode getMutatieperiode() {
        return mutatieperiode;
    }

    /**
     * Sets the value of the mutatieperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mutatieperiode }
     *     
     */
    public void setMutatieperiode(Mutatieperiode value) {
        this.mutatieperiode = value;
    }

    /**
     * Gets the value of the productcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * Sets the value of the productcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductcode(String value) {
        this.productcode = value;
    }

}
