//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.bag_verstrekkingen.extract_selecties.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  
 * 
 * <p>Java class for SchemaInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchemaInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Schemanaam" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901}Schemaversie" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="XML" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *           &lt;element name="GML" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchemaInfo", propOrder = {
    "schemanaam",
    "schemaversie",
    "xml",
    "gml"
})
public class SchemaInfo {

    @XmlElement(name = "Schemanaam")
    protected String schemanaam;
    @XmlElement(name = "Schemaversie")
    protected String schemaversie;
    @XmlElement(name = "XML", defaultValue = "0")
    protected Boolean xml;
    @XmlElement(name = "GML", defaultValue = "0")
    protected Boolean gml;

    /**
     * T.b.v. het specifiek aanvragen van een (oudere) versie van het koppelvlak.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemanaam() {
        return schemanaam;
    }

    /**
     * Sets the value of the schemanaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemanaam(String value) {
        this.schemanaam = value;
    }

    /**
     * T.b.v. het specifiek aanvragen van een (oudere) versie van het koppelvlak.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaversie() {
        return schemaversie;
    }

    /**
     * Sets the value of the schemaversie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaversie(String value) {
        this.schemaversie = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXML() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXML(Boolean value) {
        this.xml = value;
    }

    /**
     * Gets the value of the gml property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGML() {
        return gml;
    }

    /**
     * Sets the value of the gml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGML(Boolean value) {
        this.gml = value;
    }

}
