//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Een ligplaats, verblijfsobject of standplaats.
 * 
 * <p>Java class for _AdresseerbaarObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_AdresseerbaarObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gerelateerdeAdressen" type="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}GerelateerdeAdressen"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_AdresseerbaarObject", propOrder = {
    "gerelateerdeAdressen"
})
@XmlSeeAlso({
    Ligplaats.class,
    Verblijfsobject.class,
    Standplaats.class
})
public abstract class AdresseerbaarObject {

    @XmlElement(required = true)
    protected GerelateerdeAdressen gerelateerdeAdressen;

    /**
     * Gets the value of the gerelateerdeAdressen property.
     * 
     * @return
     *     possible object is
     *     {@link GerelateerdeAdressen }
     *     
     */
    public GerelateerdeAdressen getGerelateerdeAdressen() {
        return gerelateerdeAdressen;
    }

    /**
     * Sets the value of the gerelateerdeAdressen property.
     * 
     * @param value
     *     allowed object is
     *     {@link GerelateerdeAdressen }
     *     
     */
    public void setGerelateerdeAdressen(GerelateerdeAdressen value) {
        this.gerelateerdeAdressen = value;
    }

}
