//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GerelateerdeAdressen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GerelateerdeAdressen"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hoofdadres"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nevenadres" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GerelateerdeAdressen", propOrder = {
    "hoofdadres",
    "nevenadres"
})
public class GerelateerdeAdressen {

    @XmlElement(required = true)
    protected GerelateerdeAdressen.Hoofdadres hoofdadres;
    protected List<GerelateerdeAdressen.Nevenadres> nevenadres;

    /**
     * Gets the value of the hoofdadres property.
     * 
     * @return
     *     possible object is
     *     {@link GerelateerdeAdressen.Hoofdadres }
     *     
     */
    public GerelateerdeAdressen.Hoofdadres getHoofdadres() {
        return hoofdadres;
    }

    /**
     * Sets the value of the hoofdadres property.
     * 
     * @param value
     *     allowed object is
     *     {@link GerelateerdeAdressen.Hoofdadres }
     *     
     */
    public void setHoofdadres(GerelateerdeAdressen.Hoofdadres value) {
        this.hoofdadres = value;
    }

    /**
     * Gets the value of the nevenadres property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nevenadres property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNevenadres().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GerelateerdeAdressen.Nevenadres }
     * 
     * 
     */
    public List<GerelateerdeAdressen.Nevenadres> getNevenadres() {
        if (nevenadres == null) {
            nevenadres = new ArrayList<GerelateerdeAdressen.Nevenadres>();
        }
        return this.nevenadres;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificatie"
    })
    public static class Hoofdadres {

        @XmlElement(required = true)
        protected String identificatie;

        /**
         * Gets the value of the identificatie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificatie() {
            return identificatie;
        }

        /**
         * Sets the value of the identificatie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificatie(String value) {
            this.identificatie = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificatie"
    })
    public static class Nevenadres {

        @XmlElement(required = true)
        protected String identificatie;

        /**
         * Gets the value of the identificatie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificatie() {
            return identificatie;
        }

        /**
         * Sets the value of the identificatie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificatie(String value) {
            this.identificatie = value;
        }

    }

}
