//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.kadaster.schemas.imbag.lvc.v20090901 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ligplaats_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Ligplaats");
    private final static QName _AdresseerbaarObject_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "_AdresseerbaarObject");
    private final static QName _Verblijfsobject_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Verblijfsobject");
    private final static QName _GerelateerdeAdressen_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "GerelateerdeAdressen");
    private final static QName _Standplaats_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Standplaats");
    private final static QName _Pand_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Pand");
    private final static QName _Nummeraanduiding_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Nummeraanduiding");
    private final static QName _OpenbareRuimte_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "OpenbareRuimte");
    private final static QName _Woonplaats_QNAME = new QName("http://www.kadaster.nl/schemas/imbag/lvc/v20090901", "Woonplaats");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.kadaster.schemas.imbag.lvc.v20090901
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpenbareRuimte }
     * 
     */
    public OpenbareRuimte createOpenbareRuimte() {
        return new OpenbareRuimte();
    }

    /**
     * Create an instance of {@link Nummeraanduiding }
     * 
     */
    public Nummeraanduiding createNummeraanduiding() {
        return new Nummeraanduiding();
    }

    /**
     * Create an instance of {@link GerelateerdeAdressen }
     * 
     */
    public GerelateerdeAdressen createGerelateerdeAdressen() {
        return new GerelateerdeAdressen();
    }

    /**
     * Create an instance of {@link Verblijfsobject }
     * 
     */
    public Verblijfsobject createVerblijfsobject() {
        return new Verblijfsobject();
    }

    /**
     * Create an instance of {@link Ligplaats }
     * 
     */
    public Ligplaats createLigplaats() {
        return new Ligplaats();
    }

    /**
     * Create an instance of {@link Standplaats }
     * 
     */
    public Standplaats createStandplaats() {
        return new Standplaats();
    }

    /**
     * Create an instance of {@link Pand }
     * 
     */
    public Pand createPand() {
        return new Pand();
    }

    /**
     * Create an instance of {@link Woonplaats }
     * 
     */
    public Woonplaats createWoonplaats() {
        return new Woonplaats();
    }

    /**
     * Create an instance of {@link OpenbareRuimte.GerelateerdeWoonplaats }
     * 
     */
    public OpenbareRuimte.GerelateerdeWoonplaats createOpenbareRuimteGerelateerdeWoonplaats() {
        return new OpenbareRuimte.GerelateerdeWoonplaats();
    }

    /**
     * Create an instance of {@link Nummeraanduiding.GerelateerdeOpenbareRuimte }
     * 
     */
    public Nummeraanduiding.GerelateerdeOpenbareRuimte createNummeraanduidingGerelateerdeOpenbareRuimte() {
        return new Nummeraanduiding.GerelateerdeOpenbareRuimte();
    }

    /**
     * Create an instance of {@link Nummeraanduiding.GerelateerdeWoonplaats }
     * 
     */
    public Nummeraanduiding.GerelateerdeWoonplaats createNummeraanduidingGerelateerdeWoonplaats() {
        return new Nummeraanduiding.GerelateerdeWoonplaats();
    }

    /**
     * Create an instance of {@link GerelateerdeAdressen.Hoofdadres }
     * 
     */
    public GerelateerdeAdressen.Hoofdadres createGerelateerdeAdressenHoofdadres() {
        return new GerelateerdeAdressen.Hoofdadres();
    }

    /**
     * Create an instance of {@link GerelateerdeAdressen.Nevenadres }
     * 
     */
    public GerelateerdeAdressen.Nevenadres createGerelateerdeAdressenNevenadres() {
        return new GerelateerdeAdressen.Nevenadres();
    }

    /**
     * Create an instance of {@link Verblijfsobject.GerelateerdPand }
     * 
     */
    public Verblijfsobject.GerelateerdPand createVerblijfsobjectGerelateerdPand() {
        return new Verblijfsobject.GerelateerdPand();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ligplaats }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ligplaats }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Ligplaats", substitutionHeadNamespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", substitutionHeadName = "_AdresseerbaarObject")
    public JAXBElement<Ligplaats> createLigplaats(Ligplaats value) {
        return new JAXBElement<Ligplaats>(_Ligplaats_QNAME, Ligplaats.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseerbaarObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AdresseerbaarObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "_AdresseerbaarObject")
    public JAXBElement<AdresseerbaarObject> createAdresseerbaarObject(AdresseerbaarObject value) {
        return new JAXBElement<AdresseerbaarObject>(_AdresseerbaarObject_QNAME, AdresseerbaarObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Verblijfsobject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Verblijfsobject }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Verblijfsobject", substitutionHeadNamespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", substitutionHeadName = "_AdresseerbaarObject")
    public JAXBElement<Verblijfsobject> createVerblijfsobject(Verblijfsobject value) {
        return new JAXBElement<Verblijfsobject>(_Verblijfsobject_QNAME, Verblijfsobject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GerelateerdeAdressen }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GerelateerdeAdressen }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "GerelateerdeAdressen")
    public JAXBElement<GerelateerdeAdressen> createGerelateerdeAdressen(GerelateerdeAdressen value) {
        return new JAXBElement<GerelateerdeAdressen>(_GerelateerdeAdressen_QNAME, GerelateerdeAdressen.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Standplaats }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Standplaats }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Standplaats", substitutionHeadNamespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", substitutionHeadName = "_AdresseerbaarObject")
    public JAXBElement<Standplaats> createStandplaats(Standplaats value) {
        return new JAXBElement<Standplaats>(_Standplaats_QNAME, Standplaats.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pand }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Pand }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Pand")
    public JAXBElement<Pand> createPand(Pand value) {
        return new JAXBElement<Pand>(_Pand_QNAME, Pand.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nummeraanduiding }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Nummeraanduiding }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Nummeraanduiding")
    public JAXBElement<Nummeraanduiding> createNummeraanduiding(Nummeraanduiding value) {
        return new JAXBElement<Nummeraanduiding>(_Nummeraanduiding_QNAME, Nummeraanduiding.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenbareRuimte }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OpenbareRuimte }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "OpenbareRuimte")
    public JAXBElement<OpenbareRuimte> createOpenbareRuimte(OpenbareRuimte value) {
        return new JAXBElement<OpenbareRuimte>(_OpenbareRuimte_QNAME, OpenbareRuimte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Woonplaats }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Woonplaats }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", name = "Woonplaats")
    public JAXBElement<Woonplaats> createWoonplaats(Woonplaats value) {
        return new JAXBElement<Woonplaats>(_Woonplaats_QNAME, Woonplaats.class, null, value);
    }

}
