//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Bron;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Indicatie;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.StatusNaamgeving;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Tijdvakgeldigheid;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.TypeOpenbareRuimte;
import nl.studioseptember.postcode.type.BaseInterface;


/**
 * Een OPENBARE RUIMTE is een door de gemeenteraad als
 * 
 * zodanig aangewezen benaming van een binnen 1 woonplaats
 * 
 * gelegen buitenruimte.
 * 
 * <p>Java class for OpenbareRuimte complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpenbareRuimte"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
 *         &lt;element name="aanduidingRecordInactief" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="aanduidingRecordCorrectie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}indicatieCorrectie"/&gt;
 *         &lt;element name="openbareRuimteNaam" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnaam"/&gt;
 *         &lt;element name="officieel" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="tijdvakgeldigheid" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Tijdvakgeldigheid"/&gt;
 *         &lt;element name="inOnderzoek" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="openbareRuimteType" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}TypeOpenbareRuimte"/&gt;
 *         &lt;element name="bron" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Bron"/&gt;
 *         &lt;element name="openbareruimteStatus" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}StatusNaamgeving"/&gt;
 *         &lt;element name="gerelateerdeWoonplaats"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Woonplaatscode"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://www.kadaster.nl/schemas/imbag/nen5825/v20090901}VerkorteOpenbareruimteNaam" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpenbareRuimte", propOrder = {
    "identificatie",
    "aanduidingRecordInactief",
    "aanduidingRecordCorrectie",
    "openbareRuimteNaam",
    "officieel",
    "tijdvakgeldigheid",
    "inOnderzoek",
    "openbareRuimteType",
    "bron",
    "openbareruimteStatus",
    "gerelateerdeWoonplaats",
    "verkorteOpenbareruimteNaam"
})
public class OpenbareRuimte implements BaseInterface {

    @XmlElement(required = true)
    protected String identificatie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie aanduidingRecordInactief;
    @XmlElement(required = true)
    protected BigInteger aanduidingRecordCorrectie;
    @XmlElement(required = true)
    protected String openbareRuimteNaam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie officieel;
    @XmlElement(required = true)
    protected Tijdvakgeldigheid tijdvakgeldigheid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie inOnderzoek;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeOpenbareRuimte openbareRuimteType;
    @XmlElement(required = true)
    protected Bron bron;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StatusNaamgeving openbareruimteStatus;
    @XmlElement(required = true)
    protected OpenbareRuimte.GerelateerdeWoonplaats gerelateerdeWoonplaats;
    @XmlElement(name = "VerkorteOpenbareruimteNaam", namespace = "http://www.kadaster.nl/schemas/imbag/nen5825/v20090901")
    protected String verkorteOpenbareruimteNaam;

    /**
     * Gets the value of the identificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatie() {
        return identificatie;
    }

    /**
     * Sets the value of the identificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatie(String value) {
        this.identificatie = value;
    }

    /**
     * Gets the value of the aanduidingRecordInactief property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getAanduidingRecordInactief() {
        return aanduidingRecordInactief;
    }

    /**
     * Sets the value of the aanduidingRecordInactief property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setAanduidingRecordInactief(Indicatie value) {
        this.aanduidingRecordInactief = value;
    }

    /**
     * Gets the value of the aanduidingRecordCorrectie property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAanduidingRecordCorrectie() {
        return aanduidingRecordCorrectie;
    }

    /**
     * Sets the value of the aanduidingRecordCorrectie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAanduidingRecordCorrectie(BigInteger value) {
        this.aanduidingRecordCorrectie = value;
    }

    /**
     * Gets the value of the openbareRuimteNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenbareRuimteNaam() {
        return openbareRuimteNaam;
    }

    /**
     * Sets the value of the openbareRuimteNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenbareRuimteNaam(String value) {
        this.openbareRuimteNaam = value;
    }

    /**
     * Gets the value of the officieel property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getOfficieel() {
        return officieel;
    }

    /**
     * Sets the value of the officieel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setOfficieel(Indicatie value) {
        this.officieel = value;
    }

    /**
     * Gets the value of the tijdvakgeldigheid property.
     * 
     * @return
     *     possible object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public Tijdvakgeldigheid getTijdvakgeldigheid() {
        return tijdvakgeldigheid;
    }

    /**
     * Sets the value of the tijdvakgeldigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public void setTijdvakgeldigheid(Tijdvakgeldigheid value) {
        this.tijdvakgeldigheid = value;
    }

    /**
     * Gets the value of the inOnderzoek property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getInOnderzoek() {
        return inOnderzoek;
    }

    /**
     * Sets the value of the inOnderzoek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setInOnderzoek(Indicatie value) {
        this.inOnderzoek = value;
    }

    /**
     * Gets the value of the openbareRuimteType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOpenbareRuimte }
     *     
     */
    public TypeOpenbareRuimte getOpenbareRuimteType() {
        return openbareRuimteType;
    }

    /**
     * Sets the value of the openbareRuimteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOpenbareRuimte }
     *     
     */
    public void setOpenbareRuimteType(TypeOpenbareRuimte value) {
        this.openbareRuimteType = value;
    }

    /**
     * Gets the value of the bron property.
     * 
     * @return
     *     possible object is
     *     {@link Bron }
     *     
     */
    public Bron getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bron }
     *     
     */
    public void setBron(Bron value) {
        this.bron = value;
    }

    /**
     * Gets the value of the openbareruimteStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusNaamgeving }
     *     
     */
    public StatusNaamgeving getOpenbareruimteStatus() {
        return openbareruimteStatus;
    }

    /**
     * Sets the value of the openbareruimteStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusNaamgeving }
     *     
     */
    public void setOpenbareruimteStatus(StatusNaamgeving value) {
        this.openbareruimteStatus = value;
    }

    /**
     * Gets the value of the gerelateerdeWoonplaats property.
     * 
     * @return
     *     possible object is
     *     {@link OpenbareRuimte.GerelateerdeWoonplaats }
     *     
     */
    public OpenbareRuimte.GerelateerdeWoonplaats getGerelateerdeWoonplaats() {
        return gerelateerdeWoonplaats;
    }

    /**
     * Sets the value of the gerelateerdeWoonplaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenbareRuimte.GerelateerdeWoonplaats }
     *     
     */
    public void setGerelateerdeWoonplaats(OpenbareRuimte.GerelateerdeWoonplaats value) {
        this.gerelateerdeWoonplaats = value;
    }

    /**
     * Gets the value of the verkorteOpenbareruimteNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerkorteOpenbareruimteNaam() {
        return verkorteOpenbareruimteNaam;
    }

    /**
     * Sets the value of the verkorteOpenbareruimteNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerkorteOpenbareruimteNaam(String value) {
        this.verkorteOpenbareruimteNaam = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Woonplaatscode"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificatie"
    })
    public static class GerelateerdeWoonplaats {

        @XmlElement(required = true)
        protected String identificatie;

        /**
         * Gets the value of the identificatie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificatie() {
            return identificatie;
        }

        /**
         * Sets the value of the identificatie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificatie(String value) {
            this.identificatie = value;
        }

    }

}
