//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kadaster.nl/schemas/imbag/lvc/v20090901", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.kadaster.schemas.imbag.lvc.v20090901;
