//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Bron;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Gebruiksdoel;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Indicatie;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.PuntOfVlak;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.StatusVerblijfsobject;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Tijdvakgeldigheid;
import nl.studioseptember.postcode.type.BaseInterface;
import nl.studioseptember.postcode.type.VerblijfsobjectInterface;


/**
 * Een VERBLIJFSOBJECT is de kleinste binnen één of meerdere
 * 
 * panden gelegen en voor woon -, bedrijfsmatige - of recreatieve
 * 
 * doeleinden geschikte eenheid van gebruik, die ontsloten wordt
 * 
 * via een eigen toegang vanaf de openbare weg, een erf of een
 * 
 * gedeelde verkeersruimte en die onderwerp kan zijn van
 * 
 * rechtshandelingen.
 * 
 * <p>Java class for Verblijfsobject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Verblijfsobject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kadaster.nl/schemas/imbag/lvc/v20090901}_AdresseerbaarObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
 *         &lt;element name="aanduidingRecordInactief" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="aanduidingRecordCorrectie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}indicatieCorrectie"/&gt;
 *         &lt;element name="officieel" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="verblijfsobjectGeometrie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}PuntOfVlak"/&gt;
 *         &lt;element name="gebruiksdoelVerblijfsobject" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Gebruiksdoel" maxOccurs="unbounded"/&gt;
 *         &lt;element name="oppervlakteVerblijfsobject" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Oppervlaktemaat"/&gt;
 *         &lt;element name="verblijfsobjectStatus" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}StatusVerblijfsobject"/&gt;
 *         &lt;element name="tijdvakgeldigheid" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Tijdvakgeldigheid"/&gt;
 *         &lt;element name="inOnderzoek" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="bron" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Bron"/&gt;
 *         &lt;element name="gerelateerdPand" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Verblijfsobject", propOrder = {
    "identificatie",
    "aanduidingRecordInactief",
    "aanduidingRecordCorrectie",
    "officieel",
    "verblijfsobjectGeometrie",
    "gebruiksdoelVerblijfsobject",
    "oppervlakteVerblijfsobject",
    "verblijfsobjectStatus",
    "tijdvakgeldigheid",
    "inOnderzoek",
    "bron",
    "gerelateerdPand"
})
public class Verblijfsobject
    extends AdresseerbaarObject implements BaseInterface, VerblijfsobjectInterface
{

    @XmlElement(required = true)
    protected String identificatie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie aanduidingRecordInactief;
    @XmlElement(required = true)
    protected BigInteger aanduidingRecordCorrectie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie officieel;
    @XmlElement(required = true)
    protected PuntOfVlak verblijfsobjectGeometrie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected List<Gebruiksdoel> gebruiksdoelVerblijfsobject;
    @XmlSchemaType(name = "integer")
    protected int oppervlakteVerblijfsobject;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StatusVerblijfsobject verblijfsobjectStatus;
    @XmlElement(required = true)
    protected Tijdvakgeldigheid tijdvakgeldigheid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie inOnderzoek;
    @XmlElement(required = true)
    protected Bron bron;
    @XmlElement(required = true)
    protected List<Verblijfsobject.GerelateerdPand> gerelateerdPand;

    /**
     * Gets the value of the identificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatie() {
        return identificatie;
    }

    /**
     * Sets the value of the identificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatie(String value) {
        this.identificatie = value;
    }

    /**
     * Gets the value of the aanduidingRecordInactief property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getAanduidingRecordInactief() {
        return aanduidingRecordInactief;
    }

    /**
     * Sets the value of the aanduidingRecordInactief property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setAanduidingRecordInactief(Indicatie value) {
        this.aanduidingRecordInactief = value;
    }

    /**
     * Gets the value of the aanduidingRecordCorrectie property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAanduidingRecordCorrectie() {
        return aanduidingRecordCorrectie;
    }

    /**
     * Sets the value of the aanduidingRecordCorrectie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAanduidingRecordCorrectie(BigInteger value) {
        this.aanduidingRecordCorrectie = value;
    }

    /**
     * Gets the value of the officieel property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getOfficieel() {
        return officieel;
    }

    /**
     * Sets the value of the officieel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setOfficieel(Indicatie value) {
        this.officieel = value;
    }

    /**
     * Gets the value of the verblijfsobjectGeometrie property.
     * 
     * @return
     *     possible object is
     *     {@link PuntOfVlak }
     *     
     */
    public PuntOfVlak getVerblijfsobjectGeometrie() {
        return verblijfsobjectGeometrie;
    }

    /**
     * Sets the value of the verblijfsobjectGeometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link PuntOfVlak }
     *     
     */
    public void setVerblijfsobjectGeometrie(PuntOfVlak value) {
        this.verblijfsobjectGeometrie = value;
    }

    /**
     * Gets the value of the gebruiksdoelVerblijfsobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gebruiksdoelVerblijfsobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGebruiksdoelVerblijfsobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gebruiksdoel }
     * 
     * 
     */
    public List<Gebruiksdoel> getGebruiksdoelVerblijfsobject() {
        if (gebruiksdoelVerblijfsobject == null) {
            gebruiksdoelVerblijfsobject = new ArrayList<Gebruiksdoel>();
        }
        return this.gebruiksdoelVerblijfsobject;
    }

    /**
     * Gets the value of the oppervlakteVerblijfsobject property.
     * 
     */
    public int getOppervlakteVerblijfsobject() {
        return oppervlakteVerblijfsobject;
    }

    /**
     * Sets the value of the oppervlakteVerblijfsobject property.
     * 
     */
    public void setOppervlakteVerblijfsobject(int value) {
        this.oppervlakteVerblijfsobject = value;
    }

    /**
     * Gets the value of the verblijfsobjectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusVerblijfsobject }
     *     
     */
    public StatusVerblijfsobject getVerblijfsobjectStatus() {
        return verblijfsobjectStatus;
    }

    /**
     * Sets the value of the verblijfsobjectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusVerblijfsobject }
     *     
     */
    public void setVerblijfsobjectStatus(StatusVerblijfsobject value) {
        this.verblijfsobjectStatus = value;
    }

    /**
     * Gets the value of the tijdvakgeldigheid property.
     * 
     * @return
     *     possible object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public Tijdvakgeldigheid getTijdvakgeldigheid() {
        return tijdvakgeldigheid;
    }

    /**
     * Sets the value of the tijdvakgeldigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public void setTijdvakgeldigheid(Tijdvakgeldigheid value) {
        this.tijdvakgeldigheid = value;
    }

    /**
     * Gets the value of the inOnderzoek property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getInOnderzoek() {
        return inOnderzoek;
    }

    /**
     * Sets the value of the inOnderzoek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setInOnderzoek(Indicatie value) {
        this.inOnderzoek = value;
    }

    /**
     * Gets the value of the bron property.
     * 
     * @return
     *     possible object is
     *     {@link Bron }
     *     
     */
    public Bron getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bron }
     *     
     */
    public void setBron(Bron value) {
        this.bron = value;
    }

    /**
     * Gets the value of the gerelateerdPand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gerelateerdPand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGerelateerdPand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Verblijfsobject.GerelateerdPand }
     * 
     * 
     */
    public List<Verblijfsobject.GerelateerdPand> getGerelateerdPand() {
        if (gerelateerdPand == null) {
            gerelateerdPand = new ArrayList<Verblijfsobject.GerelateerdPand>();
        }
        return this.gerelateerdPand;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnummer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificatie"
    })
    public static class GerelateerdPand {

        @XmlElement(required = true)
        protected String identificatie;

        /**
         * Gets the value of the identificatie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificatie() {
            return identificatie;
        }

        /**
         * Sets the value of the identificatie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificatie(String value) {
            this.identificatie = value;
        }

    }

}
