//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 11:46:10 AM CEST 
//


package nl.kadaster.schemas.imbag.lvc.v20090901;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Bron;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Indicatie;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.StatusWoonplaats;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.Tijdvakgeldigheid;
import nl.kadaster.schemas.imbag.imbag_types.v20090901.VlakOfMultiVlak;
import nl.studioseptember.postcode.type.BaseInterface;


/**
 * Een WOONPLAATS is een door de gemeenteraad als
 * 
 * zodanig aangewezen gedeelte van het gemeentelijk
 * 
 * grondgebied.
 * 
 * <p>Java class for Woonplaats complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Woonplaats"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identificatie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Woonplaatscode"/&gt;
 *         &lt;element name="aanduidingRecordInactief" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="aanduidingRecordCorrectie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}indicatieCorrectie"/&gt;
 *         &lt;element name="woonplaatsNaam" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Objectnaam"/&gt;
 *         &lt;element name="woonplaatsGeometrie" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}VlakOfMultiVlak"/&gt;
 *         &lt;element name="officieel" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="tijdvakgeldigheid" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Tijdvakgeldigheid"/&gt;
 *         &lt;element name="inOnderzoek" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Indicatie"/&gt;
 *         &lt;element name="bron" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}Bron"/&gt;
 *         &lt;element name="woonplaatsStatus" type="{http://www.kadaster.nl/schemas/imbag/imbag-types/v20090901}StatusWoonplaats"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Woonplaats", propOrder = {
    "identificatie",
    "aanduidingRecordInactief",
    "aanduidingRecordCorrectie",
    "woonplaatsNaam",
    "woonplaatsGeometrie",
    "officieel",
    "tijdvakgeldigheid",
    "inOnderzoek",
    "bron",
    "woonplaatsStatus"
})
public class Woonplaats implements BaseInterface {

    @XmlElement(required = true)
    protected String identificatie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie aanduidingRecordInactief;
    @XmlElement(required = true)
    protected BigInteger aanduidingRecordCorrectie;
    @XmlElement(required = true)
    protected String woonplaatsNaam;
    @XmlElement(required = true)
    protected VlakOfMultiVlak woonplaatsGeometrie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie officieel;
    @XmlElement(required = true)
    protected Tijdvakgeldigheid tijdvakgeldigheid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Indicatie inOnderzoek;
    @XmlElement(required = true)
    protected Bron bron;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StatusWoonplaats woonplaatsStatus;

    /**
     * Gets the value of the identificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatie() {
        return identificatie;
    }

    /**
     * Sets the value of the identificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatie(String value) {
        this.identificatie = value;
    }

    /**
     * Gets the value of the aanduidingRecordInactief property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getAanduidingRecordInactief() {
        return aanduidingRecordInactief;
    }

    /**
     * Sets the value of the aanduidingRecordInactief property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setAanduidingRecordInactief(Indicatie value) {
        this.aanduidingRecordInactief = value;
    }

    /**
     * Gets the value of the aanduidingRecordCorrectie property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAanduidingRecordCorrectie() {
        return aanduidingRecordCorrectie;
    }

    /**
     * Sets the value of the aanduidingRecordCorrectie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAanduidingRecordCorrectie(BigInteger value) {
        this.aanduidingRecordCorrectie = value;
    }

    /**
     * Gets the value of the woonplaatsNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoonplaatsNaam() {
        return woonplaatsNaam;
    }

    /**
     * Sets the value of the woonplaatsNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoonplaatsNaam(String value) {
        this.woonplaatsNaam = value;
    }

    /**
     * Gets the value of the woonplaatsGeometrie property.
     * 
     * @return
     *     possible object is
     *     {@link VlakOfMultiVlak }
     *     
     */
    public VlakOfMultiVlak getWoonplaatsGeometrie() {
        return woonplaatsGeometrie;
    }

    /**
     * Sets the value of the woonplaatsGeometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link VlakOfMultiVlak }
     *     
     */
    public void setWoonplaatsGeometrie(VlakOfMultiVlak value) {
        this.woonplaatsGeometrie = value;
    }

    /**
     * Gets the value of the officieel property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getOfficieel() {
        return officieel;
    }

    /**
     * Sets the value of the officieel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setOfficieel(Indicatie value) {
        this.officieel = value;
    }

    /**
     * Gets the value of the tijdvakgeldigheid property.
     * 
     * @return
     *     possible object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public Tijdvakgeldigheid getTijdvakgeldigheid() {
        return tijdvakgeldigheid;
    }

    /**
     * Sets the value of the tijdvakgeldigheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tijdvakgeldigheid }
     *     
     */
    public void setTijdvakgeldigheid(Tijdvakgeldigheid value) {
        this.tijdvakgeldigheid = value;
    }

    /**
     * Gets the value of the inOnderzoek property.
     * 
     * @return
     *     possible object is
     *     {@link Indicatie }
     *     
     */
    public Indicatie getInOnderzoek() {
        return inOnderzoek;
    }

    /**
     * Sets the value of the inOnderzoek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indicatie }
     *     
     */
    public void setInOnderzoek(Indicatie value) {
        this.inOnderzoek = value;
    }

    /**
     * Gets the value of the bron property.
     * 
     * @return
     *     possible object is
     *     {@link Bron }
     *     
     */
    public Bron getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bron }
     *     
     */
    public void setBron(Bron value) {
        this.bron = value;
    }

    /**
     * Gets the value of the woonplaatsStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusWoonplaats }
     *     
     */
    public StatusWoonplaats getWoonplaatsStatus() {
        return woonplaatsStatus;
    }

    /**
     * Sets the value of the woonplaatsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusWoonplaats }
     *     
     */
    public void setWoonplaatsStatus(StatusWoonplaats value) {
        this.woonplaatsStatus = value;
    }

}
